name: Build Images

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The Kodi version'
        required: true
        default: '19.3'
      name:
        description: 'The Kodi name'
        required: true
        default: 'Matrix'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            KODI_VER=${{ github.event.inputs.version }}
            KODI_NAME=${{ github.event.inputs.name }}
            BUILDKIT_INLINE_CACHE=1
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          push: false
          tags: |
            fhriley/kodi-headless-novnc:${{ github.event.inputs.version }}
            fhriley/kodi-headless-novnc:latest
          cache-from: type=registry,ref=fhriley/kodi-headless-novnc:latest
