name: Build Images

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The Kodi version'
        required: true
        default: '19.5'
      name:
        description: 'The Kodi name'
        required: true
        default: 'Matrix'

jobs:
  build_amd64:
    uses: ./.github/workflows/build.yml
    with:
      env: ${{ github.event.inputs.environment }}
      runs_on: ubuntu-22.04
      platform: linux/amd64
      tag: amd64
      version: ${{ github.event.inputs.version }}
      name: ${{ github.event.inputs.name }}
    secrets: inherit

#   combine:
#     needs: [build_amd64, build_arm64, build_arm32]
#     runs-on: ubuntu-22.04
# 
#     steps:
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
# 
#       - 
#         name: Create and push manifest images
#         uses: Noelware/docker-manifest-action@master
#         with:
#           base-image: fhriley/kodi-headless-novnc:${{ github.event.inputs.version }}, fhriley/kodi-headless-novnc:${{ github.event.inputs.name }}
#           extra-images: fhriley/kodi-headless-novnc:${{ github.event.inputs.version }}-amd64,fhriley/kodi-headless-novnc:${{ github.event.inputs.version }}-arm64,fhriley/kodi-headless-novnc:${{ github.event.inputs.version }}-arm32
#           push: true
